stRegno = input("Enter student Register Number => ")
stName = input("Enter student Name => ")
stClass = input("Enter student Class => ")
stDept = input("Enter student Department => ")
stCollege = input("Enter student College Name => ")
stGmailId = input("Enter student Gmail ID => ")
stPhoneno = int(input("Enter student Phone Number => "))
print('='*60)
print("\tStudent Name and their details")
print('='*60)
print("Student Register Number ",stRegno,sep="=>")
print("Student Name ",stName,sep="=>")
print("Student Class ",stClass,sep="=>")
print("Student Department ",stDept,sep="=>")
print("Student College ",stCollege,sep="=>")
print("Student GMail ID ",stGmailId,sep="=>")
print("Student Phone Number ",stPhoneno,sep="=>")
print('='*60)
